deployments:
- name: cron-deploy
  version: null
  tags: ["dev"]
  description: "trigger deployment on schedule"
  schedule:
    cron: 5 * * * *
    timezone: America/Chicago
  entrypoint: prefect_homework/orchestrate.py:main_flow
  parameters: {}
  work_pool:
    name: deadpool
    work_queue_name: null